spring.application.name=TicketlordsBE

database=postgres
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://10.212.25.185:5432/ticketlords}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

