spring.application.name=TicketlordsBE

database=postgres
spring.datasource.url=jdbc:postgresql://${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
server.address=0.0.0.0
server.port=8080
#true: Shows queries, false: doesnt.
spring.jpa.show-sql=true

# JPA/Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

wishlist.page-size=8

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
